In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np
import random
import numpy as geek 

In [2]:
initial_board = geek.zeros([5, 5], dtype = int)
print(initial_board)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
class State:
    def __init__(self):
        self.father = None
        self.board = None
        
class Player:
    def __init__(self):
        self.value = None
        self.moves = 0
        self.name = None
        
def terminal_test(state):
    #Horizontal
    for i in range(5):
        if np.all(state.board[i][0:4] == 1) or np.all(state.board[i][1:5] == 1):
            return 1
        elif np.all(state.board[i][0:4] == 2) or np.all(state.board[i][1:5] == 2):
            return -1
        else:
            return 0
        
def question_place(player):
    print(f'{player.name} Ingresa la posicion xy:')
    pos = input()
    x_pos=int(pos[0])
    y_pos=int(pos[1])
    return x_pos, y_pos

def validate_place(x_pos, y_pos, board):
    if(x_pos>=0 and x_pos<5 and y_pos>=0 and y_pos<5):
        if(board[x_pos][y_pos]==0):
            return True
    return False
    
        
def init_Game(initial_board,player1,player2,movelimits):
    #start_state = State()
    #start_state.value = initial_board
    
    board=initial_board
    for i in range(4):
        #Player1
        x_pos,y_pos=question_place(player1)
        while(validate_place(x_pos,y_pos, board)==False):
            print("lugar invalido.. vuelve a intentar")
            x_pos,y_pos=question_place(player1)
        board[x_pos][y_pos]=player1.value
        print(board)
        
        #Player2
        x_pos,y_pos=question_place(player2)
        while(validate_place(x_pos,y_pos, board)==False):
            print("lugar invalido.. vuelve a intentar")
            x_pos,y_pos=question_place(player2)
        board[x_pos][y_pos]=player2.value
        print(board)



In [4]:
p1=Player()
p1.value=1
p1.name="juan"
p2=Player()
p2.value=2
p2.name="Pedro"
movelimits=30

init_Game(initial_board,p1,p2,movelimits)

juan Ingresa la posicion xy:
23
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Pedro Ingresa la posicion xy:
21
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 2 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
juan Ingresa la posicion xy:
01
[[0 1 0 0 0]
 [0 0 0 0 0]
 [0 2 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Pedro Ingresa la posicion xy:
34
[[0 1 0 0 0]
 [0 0 0 0 0]
 [0 2 0 1 0]
 [0 0 0 0 2]
 [0 0 0 0 0]]
juan Ingresa la posicion xy:
54
lugar invalido.. vuelve a intentar
juan Ingresa la posicion xy:
11
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 2 0 1 0]
 [0 0 0 0 2]
 [0 0 0 0 0]]
Pedro Ingresa la posicion xy:
22
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 2 2 1 0]
 [0 0 0 0 2]
 [0 0 0 0 0]]
juan Ingresa la posicion xy:
33
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 2 2 1 0]
 [0 0 0 1 2]
 [0 0 0 0 0]]
Pedro Ingresa la posicion xy:
44
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 2 2 1 0]
 [0 0 0 1 2]
 [0 0 0 0 2]]
